### PR TITLE
Several bug-fixes

### PR DESCRIPTION
**Pull request by pboettch**
Several bug-fixes - one per commit

### CODE REVIEW

**Comment by jeandet** [comment]
It seems that we need to double click a catalog to display it now, is that an expected behavior? @nicolasaunai is that a change you discussed with @pboettch that I missed?
The catalog filter works perfectly now.

**Comment by nicolasaunai** [comment]
Nope

**Comment by pboettch** [comment]
That's not the case on KDE/Plasma. I just have to click once. 

I switched to the activated-signal to allow re-selecting an already selected catalogue. Maybe on other windows-managers this is only triggered by a double-click.

**Comment by pboettch** [comment]
image

**Comment by pboettch** [comment]
I fixed the behavior and now reselection should work on all platforms with one click.

**Comment by jeandet** [comment]
> I fixed the behavior and now reselection should work on all platforms with one click.

@pboettch, did you forget to push? I can't see anything newer than 4 November in this PR.

**Comment by pboettch** [comment]
Yes, I forgot to push. It's done now.

**Comment by jeandet** [comment]
It looks ok now.

**Review by jeandet — APPROVED** [review]

**Pull request merged**
