### PR TITLE
Dynamic catalogue edit

### PR DESCRIPTION
**Pull request by pboettch**

### CODE REVIEW

**Comment by jeandet** [comment]
image
Isn't this supposed to filter events with col3==Turc ?

**Comment by jeandet** [comment]
image
This one is not obvious to me, any non dev user is unlikely to understand what it does and how to use it.

**Comment by pboettch** [comment]
> image Isn't this supposed to filter events with col3==Turc ?

Could you provide the json-export of this catalogue?

**Comment by jeandet** [comment]
[export_cat_icme.zip](https://github.com/SciQLop/tscat_gui/files/9624526/export_cat_icme.zip)

**Comment by pboettch** [comment]
> Isn't this supposed to filter events with col3==Turc ?

No. A predicate in a catalogue _adds_ events matching this filter to the catalogue. A catalogue is always showing all the events assigned to it.

If you create a second catalogue, a DynamicCatalogue, with your filter, it will only display the selected events.

**Review by jeandet — APPROVED** [review]
So I would say it looks OK to me, some polishing should be done in another PR but let's merge this as is.

**Pull request merged**
